# Generated by Django 4.1.3 on 2022-11-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('dueño', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('NoRecibe', 'No Recibido'), ('Recibe', 'Recibido')], default='NoRecibe', max_length=15)),
                ('destinatario', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('conserje', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Conserje'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Conserje', to=settings.AUTH_USER_MODEL)),
                ('residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.residencia')),
            ],
        ),
    ]
