# Generated by Django 4.1.4 on 2022-12-11 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('departamento', models.CharField(choices=[('1', 'UCI'), ('2', 'UTI')], max_length=20)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('No', 'No Mantencion'), ('Si', 'Mantencion')], default='No', max_length=15)),
                ('fecha_mantencion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('modelo', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
                ('residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.residencia')),
            ],
        ),
    ]
