# Generated by Django 4.1.4 on 2022-12-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='matrona',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'matrona'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='departamento',
            field=models.CharField(choices=[('UCI', 'UCI'), ('UTI', 'UTI')], max_length=20),
        ),
    ]
